### ISSUE TITLE
You can remove jquery.js

### ISSUE THREAD

**Issue by BoomerScratch** [JeffaloBob/scratch-image-uploader#1]
Scratchr2 (including the forums) already use Jquery.

**Comment by JeffaloBob** [comment]
no i can't. it won't work unless i include it unfortunately. chrome extensions are wack

**Comment by BoomerScratch** [comment]
@JeffaloBob also:
https://github.com/JeffaloBob/scratch-image-uploader/blob/d689c32370d0f8c8c6b546e9d249106038cd122d/README.md#L8
will not work because assets.scratch.mit.edu is not whitelisted.

**Comment by JeffaloBob** [comment]
> @JeffaloBob also:
> https://github.com/JeffaloBob/scratch-image-uploader/blob/d689c32370d0f8c8c6b546e9d249106038cd122d/README.md#L8
> 
> 
> will not work because assets.scratch.mit.edu is not whitelisted.

oh my... this could be bad for the french revolution.

but yeah i guess project thumbnails it is.

also do you know how to permanently delete a project without clearing trash? right now the projects just end up in the trash and it would be better for them to just disapear forever...

**Comment by BoomerScratch** [comment]
> oh my... this could be bad for the french revolution.

What
> also do you know how to permanently delete a project without clearing trash?

Nope

**Comment by mxmou** [comment]
> > oh my... this could be bad for the french revolution.
> 
> What

https://scratch.mit.edu/discuss/post/4256273/

**Comment by BoomerScratch** [comment]
I think I can close this now.
