### ISSUE TITLE
progress show more data

### ISSUE THREAD

**Issue by JeffaloBob** [JeffaloBob/scratch-image-uploader#10]
perhaps the progress indicator can show other things like what step of the process its on (eg making project, renaming...)

those don't need to be percentages, (i dont think thats possible anyways).

the main reason for this is because the indicator shows up a bit later (only when the actual upload begins) and thats makes it feel slightly slow.

**Comment by JeffaloBob** [comment]
hey @BoomerScratch could you help with this since you added it in?

**Comment by BoomerScratch** [comment]
@JeffaloBob Sure!

**Comment by JeffaloBob** [comment]
> @JeffaloBob Sure!

thank you so much :D

**Comment by BoomerScratch** [comment]
@JeffaloBob This can be closed now 😉

**Comment by JeffaloBob** [comment]
yep i'll make a new issue for error handling but i know how to do that i think

**Comment by BoomerScratch** [comment]
@JeffaloBob Can you take a look at https://github.com/JeffaloBob/scratch-image-uploader/commit/1894a0d0585310b7e461bef9e2b67a09df86fd98#commitcomment-40912614?
