### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by JeffaloBob** [JeffaloBob/scratch-image-uploader#12]
handle errors better, especially with the progress thing because if theres an error thats not with the thumbnail setting (so like an error with creating a project or setting the title) the progress display will just be stuck on the step and theres not much user feedback that an error occured.

so im thinking this would go well with #9

**Comment by BoomerScratch** [comment]
Should I do this?

**Comment by JeffaloBob** [comment]
> Should I do this?

i'll try first because i think i know how to maybe do it but if i can't figure it out then sure

**Comment by BoomerScratch** [comment]
@JeffaloBob Okay.
Hint: use `.catch()` for fetch.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Okay.
> Hint: use `.catch()` for fetch.

yep thanks!

**Comment by JeffaloBob** [comment]
@BoomerScratch i cant get my error catching to work.. is it ok if you do this one? 😅

**Comment by BoomerScratch** [comment]
@JeffaloBob Sure! Let me clone the repository and do stuff after...

**Comment by JeffaloBob** [comment]
ok thanks!

**Comment by BoomerScratch** [comment]
@JeffaloBob Pull request created! #14
