### ISSUE TITLE
cannot upload the same image using the upload button twice

### ISSUE THREAD

**Issue by JeffaloBob** [JeffaloBob/scratch-image-uploader#13]
i noticed that you cant upload the same image using the upload button twice.

steps to repro:
press upload button
select image
wait
press upload button
select the same image
nothing happens. (no errors as well)

i think this might be an issue with chrome but maybe there's something that actually isn't working

**Comment by JeffaloBob** [comment]
oh, it's a chrome thing. https://stackoverflow.com/questions/9155136/chrome-file-upload-bug-on-change-event-wont-be-executed-twice-with-the-same-fi

**Comment by BoomerScratch** [comment]
@JeffaloBob Yes, that happens when you upload the same file twice. It's hard to fix, though.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Yes, when you upload the same file twice `onchange` doesn't fire. It's hard to fix, though.
> Also, take a look at #14 😉

thanks! i just submitted a fix for this and it seems to work for me. does it work for you?

**Comment by JeffaloBob** [comment]
i'll close this issue since i think it's fixed
