### ISSUE TITLE
Project still appears in my stuff, but also in the trash folder. (gets duplicated for some reason)

### ISSUE THREAD

**Issue by BoomerScratch** [JeffaloBob/scratch-image-uploader#5]
My own version (userscript) does move it to the trash folder, without letting it appear in 'my stuff'. I don't want to install any new extensions so I copy and pasted the code of the extension in the JS console.

**Comment by JeffaloBob** [comment]
that's very odd, it should not do that. i can't manage to reproduce this bug, it might have to do with running it in the javascript console. are there any errors? 

why don't you want to install any new extensions anyways?

**Comment by BoomerScratch** [comment]
@JeffaloBob I did it again and this time it didn't happen.

**Comment by JeffaloBob** [comment]
> @JeffaloBob I did it again and this time it didn't happen.

thats very odd. did you by any chance note down the project ids? perhaps you can have two projects with the same id. that would be very odd
