### ISSUE TITLE
Making this a userscript too?

### ISSUE THREAD

**Issue by BoomerScratch** [JeffaloBob/scratch-image-uploader#6]
Making a userscript out of this is very simple. It will look like something like this:
```javascript
// ==UserScript==
// @name         Scratch image uploader
// @namespace    https://jeffalo.net/
// @version      1.0
// @description  Image uploader for the Scratch forums, that uses project thumbnails
// @author       Jeffalo
// @icon         https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/images/logo_1000.png
// @include      https://scratch.mit.edu/discuss/*
// @require      https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/text-field-edit.js
// @grant        none
// ==/UserScript==

// The content of content.js goes here
```
You can change `@name`, `@namespace`, `@version`, `@description`, and `@author` if you want. Also, replace `// The content of content.js goes here` with [this](https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/content.js).

**Comment by BoomerScratch** [comment]
This _might_ work too:
```javascript
// ==UserScript==
// @name         Scratch image uploader
// @namespace    https://jeffalo.net/
// @version      1.0
// @description  Image uploader for the Scratch forums, that uses project thumbnails
// @author       Jeffalo
// @icon         https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/images/logo_1000.png
// @include      https://scratch.mit.edu/discuss/*
// @require      https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/text-field-edit.js
// @require      https://raw.githubusercontent.com/JeffaloBob/scratch-image-uploader/master/content.js
// @grant        none
// ==/UserScript==
```
If you use this, then you don't have to change this userscript every time you change content.js.

**Comment by JeffaloBob** [comment]
awesome! put this in the readme.md

**Comment by BoomerScratch** [comment]
@JeffaloBob I recommend https://github.com/JeffaloBob/scratch-image-uploader/issues/6#issuecomment-663960337, but it might take a little longer to load.

**Comment by JeffaloBob** [comment]
> @JeffaloBob I recommend [#6 (comment)](https://github.com/JeffaloBob/scratch-image-uploader/issues/6#issuecomment-663960337), but it might take a little longer to load.

yep, thats what i used because it'll auto update.
